CREATE DATABASE IF NOT EXISTS src_db;

CREATE DATABASE IF NOT EXISTS dest_db;

DROP TABLE IF EXISTS src_db.t1;

DROP TABLE IF EXISTS src_db.t2;

CREATE TABLE IF NOT EXISTS src_db.t1
(
name STRING,
P int
)
USING PARQUET
PARTITIONED BY (P);

CREATE TABLE IF NOT EXISTS src_db.t2
(
name STRING,
P int
)
USING PARQUET
PARTITIONED BY (P);

INSERT OVERWRITE TABLE src_db.t1 PARTITION (P=1)
  VALUES
('1a'), ('1b');

INSERT OVERWRITE TABLE src_db.t1 PARTITION (P=2)
  VALUES
('2c'), ('2d');

INSERT OVERWRITE TABLE src_db.t1 PARTITION (P=4)
  VALUES
('4g');

INSERT OVERWRITE TABLE src_db.t2 PARTITION (P=101)
  VALUES
('101a'), ('101b');

INSERT OVERWRITE TABLE src_db.t2 PARTITION (P=102)
  VALUES
('102a'), ('102b');

INSERT OVERWRITE TABLE src_db.t2 PARTITION (P=104)
  VALUES
('104g');

DROP TABLE IF EXISTS dest_db.t1;

DROP TABLE IF EXISTS dest_db.t2;

CREATE TABLE IF NOT EXISTS dest_db.t1
(
name STRING,
P int
)
USING PARQUET
PARTITIONED BY (P);

CREATE TABLE IF NOT EXISTS dest_db.t2
(
name STRING,
P int
)
USING PARQUET
PARTITIONED BY (P);

INSERT OVERWRITE TABLE dest_db.t1 PARTITION (P=1)
  VALUES
('__1a'), ('__1b');

INSERT OVERWRITE TABLE dest_db.t1 PARTITION (P=2)
  VALUES
('__2c'), ('__2d');

INSERT OVERWRITE TABLE dest_db.t1 PARTITION (P=3)
  VALUES
('__3e'), ('__3f');



INSERT OVERWRITE TABLE dest_db.t2 PARTITION (P=101)
  VALUES
('__101a'), ('__101b');

INSERT OVERWRITE TABLE dest_db.t2 PARTITION (P=102)
  VALUES
('__102a'), ('__102b');

INSERT OVERWRITE TABLE dest_db.t2 PARTITION (P=103)
  VALUES
('__103e'), ('__103f');
